# Generated by Django 5.0.7 on 2024-10-10 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi'])]),
        ),
    ]
