# Generated by Django 5.0.7 on 2024-10-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment_student_reaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_reaction',
            new_name='StudentReaction',
        ),
    ]
