# Generated by Django 5.0.7 on 2024-10-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_student_reaction_studentreaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreaction',
            old_name='reaction',
            new_name='liked_it',
        ),
    ]
