# Generated by Django 5.0.7 on 2024-10-10 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_reaction_studentreaction_liked_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.lesson'),
        ),
        migrations.AlterField(
            model_name='studentreaction',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.lesson'),
        ),
    ]
