# Generated by Django 5.0.7 on 2024-10-12 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreaction',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson'),
        ),
    ]
