# Generated by Django 5.0.7 on 2024-10-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_comment_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='student',
        ),
        migrations.AddField(
            model_name='comment',
            name='lesson',
            field=models.ManyToManyField(to='main.lesson'),
        ),
        migrations.AddField(
            model_name='comment',
            name='student',
            field=models.ManyToManyField(to='main.student'),
        ),
    ]
