# Generated by Django 5.0.7 on 2024-10-12 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_comment_lesson_remove_comment_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='student',
        ),
        migrations.AddField(
            model_name='comment',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
            preserve_default=False,
        ),
    ]
