# Generated by Django 5.1.1 on 2024-09-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_car_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=1, upload_to='car/'),
            preserve_default=False,
        ),
    ]
